days:
  - date: "2018-02-14"
    source_date_label: Wednesday-14-02-2018
    attacks:
      - name: FTP-BruteForce
        rules:
          - label: "FTP-BruteForce"
            start: "2018-02-14T14:33:26Z"
            finish: "2018-02-14T16:10:31Z"
            src_ips: ["18.221.219.4"]
            dst_ips: ["172.31.69.25"]
          - label: "FTP-BruteForce"
            start: "2018-02-14T18:01:21.199541Z"
            finish: "2018-02-14T18:01:21.502585Z"
            src_ips: ["13.58.98.64"]
            dst_ips: ["172.31.69.25"]
            dst_ports: [21]
      - name: SSH-Bruteforce
        rules:
          - label: "SSH-Bruteforce"
            start: "2018-02-14T18:01:50Z"
            finish: "2018-02-14T19:32:30Z"
            src_ips: ["13.58.98.64"]
            dst_ips: ["172.31.69.25"]
            dst_ports: [22]

  - date: "2018-02-15"
    source_date_label: Thursday-15-02-2018
    attacks:
      - name: DoS attacks-GoldenEye
        rules:
          - label: "DoS attacks-GoldenEye"
            start: "2018-02-15T13:27:42Z"
            finish: "2018-02-15T14:11:45Z"
            src_ips: ["18.219.211.138"]
            dst_ips: ["172.31.69.25"]
      - name: DoS attacks-Slowloris
        rules:
          - label: "DoS attacks-Slowloris"
            start: "2018-02-15T15:00:12Z"
            finish: "2018-02-15T15:42:01Z"
            src_ips: ["18.217.165.70"]
            dst_ips: ["172.31.69.25"]

  - date: "2018-02-16"
    source_date_label: Friday-16-02-2018
    attacks:
      - name: FTP-BruteForce
        rules:
          - label: "FTP-BruteForce"
            start: "2018-02-16T14:12:14Z"
            finish: "2018-02-16T15:05:13Z"
            src_ips: ["13.59.126.31"]
            dst_ips: ["172.31.69.25"]
      - name: DoS attacks-Hulk
        rules:
          - label: "DoS attacks-Hulk"
            start: "2018-02-16T17:45:27Z"
            finish: "2018-02-16T17:58:23Z"
            src_ips: ["18.219.193.20"]
            dst_ips: ["172.31.69.25"]

  - date: "2018-02-20"
    source_date_label: Tuesday-20-02-2018
    attacks:
      - name: DDoS attacks-LOIC-HTTP
        rules:
          - label: "DDoS attacks-LOIC-HTTP"
            start: "2018-02-20T14:13:54Z"
            finish: "2018-02-20T15:16:49Z"
            src_ips: &ddos_attackers_feb20
              - "18.218.115.60"
              - "18.219.9.1"
              - "18.219.32.43"
              - "18.218.55.126"
              - "52.14.136.135"
              - "18.219.5.43"
              - "18.216.200.189"
              - "18.218.229.235"
              - "18.218.11.51"
              - "18.216.24.42"
            dst_ips: ["172.31.69.25"]
            protocol: 6
      - name: DDOS attack-LOIC-UDP
        rules:
          - label: "DDOS attack-LOIC-UDP"
            start: "2018-02-20T17:14:17Z"
            finish: "2018-02-20T17:29:16Z"
            src_ips: *ddos_attackers_feb20
            dst_ips: ["172.31.69.25"]
            protocol: 17

  - date: "2018-02-21"
    source_date_label: Wednesday-21-02-2018
    attacks:
      - name: DDOS attack-LOIC-UDP
        rules:
          - label: "DDOS attack-LOIC-UDP"
            start: "2018-02-21T14:08:51Z"
            finish: "2018-02-21T14:43:39Z"
            src_ips: *ddos_attackers_feb20
            dst_ips: ["172.31.69.28"]
            protocol: 17
      - name: DDOS attack-HOIC
        rules:
          - label: "DDOS attack-HOIC"
            start: "2018-02-21T18:11:08Z"
            finish: "2018-02-21T19:05:55Z"
            src_ips: *ddos_attackers_feb20
            dst_ips: ["172.31.69.28"]
            protocol: 6

  - date: "2018-02-22"
    source_date_label: Thursday-22-02-2018
    attacks:
      - name: SQL Injection
        rules:
          - label: "SQL Injection"
            start: "2018-02-22T20:14:30.169342Z"
            finish: "2018-02-22T20:14:58.599986Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
          - label: "SQL Injection"
            start: "2018-02-22T20:16:30.418906Z"
            finish: "2018-02-22T20:27:56.022793Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
      - name: Brute Force -XSS
        rules:
          - label: "Brute Force -XSS"
            start: "2018-02-22T17:51:39.783923Z"
            finish: "2018-02-22T18:29:41.827037Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
      - name: Brute Force -Web
        rules:
          - label: "Brute Force -Web"
            start: "2018-02-22T14:13:44.965705Z"
            finish: "2018-02-22T14:15:47.920399Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
          - label: "Brute Force -Web"
            start: "2018-02-22T14:17:51.336902Z"
            finish: "2018-02-22T15:23:59.858533Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]

  - date: "2018-02-23"
    source_date_label: Friday-23-02-2018
    attacks:
      - name: SQL Injection
        rules:
          - label: "SQL Injection"
            start: "2018-02-23T19:05:22.675686Z"
            finish: "2018-02-23T19:06:27.879296Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
          - label: "SQL Injection"
            start: "2018-02-23T19:06:32.126122Z"
            finish: "2018-02-23T19:17:24.947957Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
      - name: Brute Force -XSS
        rules:
          - label: "Brute Force -XSS"
            start: "2018-02-23T17:01:04.559707Z"
            finish: "2018-02-23T18:10:28.237472Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]
      - name: Brute Force -Web
        rules:
          - label: "Brute Force -Web"
            start: "2018-02-23T14:04:30.193975Z"
            finish: "2018-02-23T15:03:06.406294Z"
            src_ips: ["18.218.115.60"]
            dst_ips: ["172.31.69.28"]

  - date: "2018-02-28"
    source_date_label: Wednesday-28-02-2018
    attacks:
      - name: Infilteration
        rules:
          - label: "Infilteration"
            start: "2018-02-28T14:33:24Z"
            finish: "2018-02-28T14:46:12Z"
            src_ips: ["172.31.69.24"]
            dst_ips:
              - "162.125.3.1"
              - "162.125.3.5"
              - "162.125.3.6"
              - "162.125.248.1"
              - "162.125.18.133"
              - "104.16.100.29"
              - "104.16.99.29"
              - "52.84.128.3"
              - "52.85.101.236"
              - "52.85.131.81"
              - "52.85.95.206"
          - label: "Infilteration"
            start: "2018-02-28T17:42:51Z"
            finish: "2018-02-28T17:43:44Z"
            src_ips: ["172.31.69.24"]
            dst_ips:
              - "162.125.3.1"
              - "162.125.3.5"
              - "162.125.3.6"
              - "162.125.248.1"
              - "162.125.18.133"
              - "104.16.100.29"
              - "104.16.99.29"
              - "52.84.128.3"
              - "52.85.101.236"
              - "52.85.131.81"
              - "52.85.95.206"
          - label: "Infilteration"
            start: "2018-02-28T14:45:40Z"
            finish: "2018-02-28T16:08:55Z"
            src_ips: ["172.31.69.24"]
            dst_ips: ["13.58.225.34"]
          - label: "Infilteration"
            start: "2018-02-28T17:43:59Z"
            finish: "2018-02-28T18:40:00Z"
            src_ips: ["172.31.69.24"]
            dst_ips: ["13.58.225.34"]
          - label: "Infilteration"
            start: "2018-02-28T14:46:22Z"
            finish: "2018-02-28T18:39:00.746247Z"
            src_ips: ["172.31.69.24"]
            dst_ips:
              - "172.31.69.1"
              - "172.31.69.10"
              - "172.31.69.11"
              - "172.31.69.12"
              - "172.31.69.13"
              - "172.31.69.14"
              - "172.31.69.16"
              - "172.31.69.17"
              - "172.31.69.19"
              - "172.31.69.20"
              - "172.31.69.23"
              - "172.31.69.4"
              - "172.31.69.5"
              - "172.31.69.6"
              - "172.31.69.8"
              - "172.31.69.9"
              - "172.31.69.7"
              - "172.31.69.22"
              - "172.31.69.15"
              - "172.31.69.21"
              - "172.31.69.18"
            extra_conditions:
              - {feature: "Source Port", op: "ne", value: 68}

  - date: "2018-03-01"
    source_date_label: Thursday-01-03-2018
    attacks:
      - name: Infilteration
        rules:
          - label: "Infilteration"
            start: "2018-03-01T13:53:10Z"
            finish: "2018-03-01T13:59:20Z"
            src_ips: ["172.31.69.13"]
            dst_ips:
              - "162.125.3.1"
              - "162.125.3.6"
              - "162.125.248.1"
              - "162.125.18.133"
              - "104.16.100.29"
              - "13.32.168.125"
              - "52.85.112.72"
          - label: "Infilteration"
            start: "2018-03-01T14:03:52Z"
            finish: "2018-03-01T15:34:14Z"
            src_ips: ["172.31.69.13"]
            dst_ips:
              - "162.125.3.1"
              - "162.125.3.6"
              - "162.125.248.1"
              - "162.125.18.133"
              - "104.16.100.29"
              - "13.32.168.125"
              - "52.85.112.72"
          - label: "Infilteration"
            start: "2018-03-01T13:57:54Z"
            finish: "2018-03-01T13:59:05Z"
            src_ips: ["172.31.69.13"]
            dst_ips: ["13.58.225.34"]
          - label: "Infilteration"
            start: "2018-03-01T14:04:35Z"
            finish: "2018-03-01T18:17:25Z"
            src_ips: ["172.31.69.13"]
            dst_ips: ["13.58.225.34"]
          - label: "Infilteration"
            start: "2018-03-01T18:18:15Z"
            finish: "2018-03-01T19:37:21Z"
            src_ips: ["172.31.69.13"]
            dst_ips: ["13.58.225.34"]
          - label: "Infilteration"
            start: "2018-03-01T14:09:48.354333Z"
            finish: "2018-03-01T19:38:12.182726Z"
            src_ips: ["172.31.69.13"]
            dst_ips:
              - "172.31.69.1"
              - "172.31.69.11"
              - "172.31.69.12"
              - "172.31.69.16"
              - "172.31.69.8"
              - "172.31.69.9"
              - "172.31.69.10"
              - "172.31.69.14"
              - "172.31.69.4"
              - "172.31.69.5"
              - "172.31.69.6"
              - "172.31.69.17"
              - "172.31.69.20"
              - "172.31.69.23"
              - "172.31.69.24"
              - "172.31.69.19"
              - "172.31.69.7"
              - "172.31.69.15"
              - "172.31.69.18"
              - "172.31.69.22"
              - "172.31.69.21"
            extra_conditions:
              - {feature: "Source Port", op: "ne", value: 68}

  - date: "2018-03-02"
    source_date_label: Friday-02-03-2018
    attacks:
      - name: Bot
        rules:
          - label: "Bot"
            start: "2018-03-02T14:13:28Z"
            finish: "2018-03-02T19:54:52Z"
            extra_conditions:
              - any_of:
                  - {feature: "Source IP", op: "eq", value: "18.219.211.138"}
                  - {feature: "Destination IP", op: "eq", value: "18.219.211.138"}